version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    AWS_ACCOUNT_ID: 156916773321
    ECR_REPO: jayamaran/sample-for-ecs
    ECR_REGISTRY: 156916773321.dkr.ecr.ap-south-1.amazonaws.com
    IMAGE_TAG: latest
    BASE_IMAGE: 156916773321.dkr.ecr.ap-south-1.amazonaws.com/jayamaran/sample-for-ecs:base
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo Building the Docker image...
      - docker build -f Dockerfile.app --build-arg BASE_IMAGE=$BASE_IMAGE -t $ECR_REPO:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
      - echo Build and push complete.

# Optional: remove this if CodePipeline or S3 doesn't require artifacts
artifacts:
  files:
    - '**/*'
