version: 0.2

env:
  secrets-manager:
    ECR_URI: "Jai-Terraform-Secret:ECR_URI"

phases:
  install:
    commands:
       - Buggy-App/scripts/install.sh

  build:
    commands:
      - docker build -f Buggy-App/Dockerfile.app -t $BUGGY_APP Buggy-App/
      
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $BUGGY_APP
      - echo "Docker image pushed successfully."
      - echo "Creating imagedefinitions.json for ECS..."
      - printf '[{"name":"buggy-web","imageUri":"%s"}]' "$BUGGY_APP" > imagedefinitions.json
      - echo "Running Terraform in Buggy-App/Terraform..."
      - cd Buggy-App/Terraform
      - terraform init
      - terraform apply --auto-approve -var="image=$BUGGY_APP" -var-file=terraform.tfvars

artifacts:
  files:
    - imagedefinitions.json
