version: 0.2

env:
  variables:
    ECR_URI: "156916773321.dkr.ecr.ap-south-1.amazonaws.com/jayamaran/sample-for-ecs"

phases:
  install:
    commands:
      - echo Installing Terraform...
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - echo Installing Docker (if not already present)...
      - amazon-linux-extras install docker -y
      - service docker start

  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_URI
      - echo Determining commit ID for tagging Docker image...
      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-10)
      - BUGGY_APP="${ECR_URI}:${COMMIT_ID}"
      - echo "Docker image will be tagged as $BUGGY_APP"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build --no-cache -f Buggy-App/Dockerfile.app -t $BUGGY_APP Buggy-App/

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $BUGGY_APP
      - echo "Docker image pushed successfully."
      - echo "Creating imagedefinitions.json for ECS..."
      - printf '[{"name":"buggy-web","imageUri":"%s"}]' "$BUGGY_APP" > imagedefinitions.json
      - echo "Changing directory to Terraform folder..."
      - cd $CODEBUILD_SRC_DIR/Buggy-App/Terraform
      - echo "Listing Terraform files..."
      - ls -la
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Applying Terraform with new Docker image..."
      - terraform apply --auto-approve -var="image=$BUGGY_APP" -var-file=terraform.tfvars

artifacts:
  files:
    - imagedefinitions.json
