version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: buggy-db-pipeline
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: buggy-web-pipeline
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:stable-alpine
    container_name: buggy-nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/app/public:ro

volumes:
  db_data:
